defaultPlacement: end
enableVersioning: true
entryTypes:
  - uid: 65e75b6f-8a8e-42e4-8e0a-56b3e1def767 # Meeting
handle: meetings
maxAuthors: 1
minAuthors: 1
name: Meetings
propagationMethod: all
siteSettings:
  5db173fa-6784-482f-a62e-4417081cd07f: # Eventful Demo
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
